topics:
  - name: "/camera/color/camera_info"
    type: "sensor_msgs/msg/CameraInfo"
  - name: "/tf"
    type: "tf2_msgs/msg/TFMessage"
  - name: "/joint_states"
    type: "sensor_msgs/msg/JointState"

# Global settings
output_format: "json"  # Options: console, json, csv
update_rate: 10.0  # Hz
use_plugins: true  # Whether to use message type-specific plugins 